openapi: 3.0.0
servers:
  - description: local server
    url: 'http://localhost:8000/api'
info:
  description: this is sofra food ordering app documentation
  version: 1.0.0
  title: Sofra Apis
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: mhmudee@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
tags:
  - name: client
    description: client requests
  - name: restaurant
    description: restaurant requests
paths:
  /client/register:
    post:
      tags:
        - client
      summary: register client to Sofra
      operationId: registerClient
      responses:
        '200':
          description: success client registered
        '400':
          description: Invalid input
      security: []
      requestBody:
        $ref: '#/components/requestBodies/ClientRegister'
components:
  schemas:
    Client:
      type: object
      required:
        - name
        - email
        - phone
        - address
        - password
        - password_confirmation
        - city
        - neighborhood
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
        city:
          type: integer
        neighborhood:
          type: integer
  requestBodies:
    ClientRegister:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Client'
      description: Client object that needs to be added to the sofra app
      required: true

  securitySchemes:
    ClientBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    RestBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
